(function(){
  const key='adapteduca_questionnaire_draft';
  const steps=[
    {title:'Perfil do Aluno',render:()=>`<div class="question-block"><h3><span class="qnum">1.</span>Qual matéria você tem mais dificuldade?</h3>${radio('dificuldade',['Matemática','Português','História','Geografia','Ciências/Biologia','Física','Química','Inglês'])}<input class="input" name="dificuldadeOutra" placeholder="Outra: escreva aqui..." style="margin-top:10px"></div><div class="form-row" style="margin-top:18px"><div class="input-group"><label>Nome</label><input class="input" name="nome" required></div><div class="input-group"><label>Idade</label><input class="input" type="number" min="6" max="100" name="idade" required></div><div class="input-group"><label>Série</label><input class="input" name="serie" placeholder="Ex.: 9º Ano" required></div><div class="input-group"><label>Escola</label><input class="input" name="escola" required></div></div>`},
    {title:'Como Você Aprende Melhor',render:()=>`${question('2.','Quando você está aprendendo algo novo, o que mais ajuda?','novo',['Ver imagens, gráficos ou mapas mentais.','Ouvir uma explicação.','Ler textos e fazer anotações.','Fazer exercícios e colocar a mão na massa.'])}${question('3.','Em uma aula, você aprende mais quando:','aula',['O professor usa slides e imagens.','O professor explica falando.','Você acompanha por um livro ou apostila.','Você faz atividades durante a aula.'])}${question('4.','Quando precisa lembrar de um conteúdo, você normalmente:','lembrar',['Lembra das imagens ou cores.','Lembra do que ouviu.','Lembra do que escreveu.','Lembra da prática ou de um exercício.'])}${question('5.','Você aprende melhor quando o professor:','professor',['Explica passo a passo.','Faz demonstrações.','Conta histórias.','Faz perguntas.','Passa exercícios.'])}${question('6.','Você aprende melhor quando:','estrutura',['Existe bastante interação.','O conteúdo é curto e objetivo.','O conteúdo é bem detalhado.','Há exemplos práticos.'])}${question('7.','Você prefere conteúdos:','preferenciaConteudo',['Curtos e objetivos.','Detalhados.','Divididos em pequenas partes.','Com muitos exemplos.'])}`},
    {title:'Formatos Preferidos',render:()=>`<div class="question-block"><h3><span class="qnum">8.</span>Como você aprende melhor? Selecione uma ou mais opções.</h3>${checkbox('formats',['Lendo textos','Vídeos','Áudios','Resumos','Mapas Mentais','Infográficos','Exercícios','Flashcards'])}</div>`},
    {title:'Horário de Estudo',render:()=>question('9.','Qual é o melhor horário para estudar?','horario',['Manhã','Tarde','Noite'])},
    {title:'Tempo de Concentração',render:()=>question('10.','Por quanto tempo você costuma manter a concentração?','concentracao',['Menos de 15 minutos','15 a 30 minutos','30 a 60 minutos','Mais de 1 hora'])},
    {title:'Necessidades Educacionais',render:()=>`<div class="question-block"><h3><span class="qnum">11.</span>Selecione as necessidades educacionais que se aplicam.</h3>${checkbox('necessidades',['TDAH','TEA','Dislexia','Discalculia','Baixa visão','Deficiência auditiva','Nenhuma','Outro'])}<input class="input" name="necessidadeOutra" placeholder="Descreva outra necessidade" style="margin-top:10px"></div>`},
    {title:'Preferência de Explicação',render:()=>`<div class="question-block"><h3><span class="qnum">12.</span>Como você prefere as explicações?</h3>${checkbox('explicacoes',['Objetivas','Detalhadas','Passo a passo','Com exemplos','Com imagens'])}</div>`},
    {title:'Conteúdo e Avaliação',render:()=>`${question('13.','Qual tamanho de conteúdo você prefere?','tamanho',['Curto','Médio','Longo'])}${question('14.','Qual forma de avaliação você prefere?','avaliacao',['Questões objetivas','Questões discursivas','Exercícios','Flashcards','Quiz'])}`},
    {title:'Revisão e Finalização',render:()=>`<div class="completion"><div class="success-ring">✓</div><h2>Seu perfil está quase pronto!</h2><p>Revise suas escolhas e conclua o perfil. Você poderá editar essas informações posteriormente no seu perfil.</p><div id="reviewAnswers" class="card" style="text-align:left;padding:18px"></div></div>`}
  ];
  let current=0,answers={};
  function radio(name,items){return `<div class="choice-list">${items.map(i=>`<label class="choice"><input type="radio" name="${name}" value="${i}" required><span>${i}</span></label>`).join('')}</div>`}
  function checkbox(name,items){return `<div class="choice-list">${items.map(i=>`<label class="choice checkbox"><input type="checkbox" name="${name}" value="${i}"><span>${i}</span></label>`).join('')}</div>`}
  function question(num,title,name,items){return `<div class="question-block"><h3><span class="qnum">${num}</span>${title}</h3>${radio(name,items)}</div>`}
  function readDraft(){try{answers=JSON.parse(localStorage.getItem(key)||'{}')}catch{answers={}}}
  function collect(){const form=document.querySelector('#questionnaireForm');if(!form)return;const fd=new FormData(form);for(const [k,v] of fd){if(['formats','necessidades','explicacoes'].includes(k)){answers[k]=answers[k]||[];if(!answers[k].includes(v))answers[k].push(v)}else answers[k]=v}localStorage.setItem(key,JSON.stringify(answers))}
  function restore(){const form=document.querySelector('#questionnaireForm');if(!form)return;Object.entries(answers).forEach(([name,value])=>{const fields=[...form.querySelectorAll(`[name="${name}"]`)];fields.forEach(field=>{if(field.type==='radio')field.checked=field.value===value;else if(field.type==='checkbox')field.checked=Array.isArray(value)&&value.includes(field.value);else field.value=value||''})})}
  function validate(){const form=document.querySelector('#questionnaireForm');const required=[...form.querySelectorAll('[required]')];if(required.some(i=>!i.checkValidity())){form.reportValidity();return false}if(current===2&&!form.querySelector('[name="formats"]:checked')){showToast('Selecione ao menos um formato de aprendizagem.','error');return false}return true}
  function render(){const host=document.querySelector('#questionnaireStep');if(!host)return;const step=steps[current];host.innerHTML=`<div class="question-section-title"><span class="step-number">${current+1}</span><strong>${step.title}</strong></div>${step.render()}<div class="question-nav"><button class="btn btn-light" type="button" id="prevStep" ${current===0?'disabled':''}>‹ Anterior</button><button class="btn btn-primary" type="button" id="nextStep">${current===steps.length-1?'Concluir Perfil':'Próxima ›'}</button></div>`;document.querySelector('#stepLabel').textContent=`Seção ${current+1} de ${steps.length}`;document.querySelector('#stepPercent').textContent=`${Math.round((current+1)/steps.length*100)}% concluído`;document.querySelector('#stepBar').style.width=`${(current+1)/steps.length*100}%`;restore();if(current===steps.length-1)renderReview();document.querySelector('#prevStep').onclick=()=>{collect();current--;render();window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('#nextStep').onclick=()=>{if(!validate())return;collect();if(current===steps.length-1){AdaptAuth.completeQuestionnaire(answers);localStorage.removeItem(key);host.innerHTML=`<div class="completion"><div class="success-ring">✓</div><h2>Perfil de aprendizagem concluído com sucesso!</h2><p>Agora nossa IA poderá adaptar os conteúdos enviados pelos seus professores da maneira mais eficiente para você.</p><button class="btn btn-primary" id="goDashboard">Ir para o Dashboard</button></div>`;document.querySelector('#goDashboard').onclick=()=>AdaptAuth.goToDashboard();return}current++;render();window.scrollTo({top:0,behavior:'smooth'})}}
  function renderReview(){const review=document.querySelector('#reviewAnswers');if(!review)return;review.innerHTML=Object.entries(answers).filter(([,v])=>v&&(!Array.isArray(v)||v.length)).map(([k,v])=>`<p style="margin-bottom:8px"><strong>${k.replace(/([A-Z])/g,' $1')}:</strong> ${Array.isArray(v)?v.join(', '):v}</p>`).join('')||'<p class="muted">As respostas aparecerão aqui.</p>'}
  document.addEventListener('DOMContentLoaded',()=>{if(!document.querySelector('#questionnaireStep'))return;readDraft();render()});
})();
