(function(){
  window.showToast=function(message,type='success'){const stack=document.querySelector('#toastStack')||document.body;const toast=document.createElement('div');toast.className=`toast ${type}`;toast.textContent=message;stack.appendChild(toast);setTimeout(()=>toast.remove(),3200)};
  window.openModal=function(title,content,actions=''){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="modal-head"><h2 id="modalTitle">${title}</h2><button class="modal-close" aria-label="Fechar">×</button></div><div>${content}</div>${actions?`<div style="display:flex;justify-content:flex-end;gap:10px;margin-top:20px">${actions}</div>`:''}</section>`;document.body.appendChild(wrap);wrap.querySelector('.modal-close').focus();const close=()=>wrap.remove();wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('.modal-close'))close()});document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}})};
  document.addEventListener('DOMContentLoaded',()=>{
    document.querySelectorAll('[data-modal-message]').forEach(btn=>btn.addEventListener('click',()=>openModal(btn.dataset.modalTitle||'AdaptEduca',`<p class="muted">${btn.dataset.modalMessage}</p>`)));
    document.querySelectorAll('[data-password-toggle]').forEach(btn=>btn.addEventListener('click',()=>{const input=document.querySelector(btn.dataset.passwordToggle);if(input){input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'◉':'⊘'}}));
    document.querySelectorAll('.role-option').forEach(option=>option.addEventListener('click',()=>{document.querySelectorAll('.role-option').forEach(o=>o.classList.remove('selected'));option.classList.add('selected');option.querySelector('input').checked=true}));
    document.querySelectorAll('[data-tabs]').forEach(group=>{group.addEventListener('click',e=>{const btn=e.target.closest('[data-tab]');if(!btn)return;group.querySelectorAll('[data-tab]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const target=btn.dataset.tab;document.querySelectorAll(`[data-tab-panel-group="${group.dataset.tabs}"]`).forEach(p=>p.hidden=p.dataset.tabPanel!==target)})});
  });
})();
